const styleClass = {
  label: 'block pl-1 text-sm font-medium text-gray-900 dark:text-gray-400',
  navlink: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent",
  input: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-700 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
  select: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-800 dark:border-gray-700 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
  btn: "h-10 font-medium rounded-lg px-4 py-2 text-sm focus:ring focus:outline-none transition-bg duration-500",
  btn2: "text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700 transition-bg duration-500",
  table: "w-full text-sm text-left text-gray-500 dark:text-gray-400",
  thead: "bg-white dark:bg-gray-800 text-gray-700  dark:text-gray-400",
  th: "px-6 py-3 select-none text-xs text-gray-700 uppercase dark:text-gray-400",
  tr: "border-b border-gray-200 dark:border-gray-700",
  td: "px-6 py-3 select-none",
  tdclick: "px-6 py-3 select-none cursor-pointer font-semibold hover:text-green-400",
  trh: "text-md font-semibold",
  tdh: "px-6 py-2 select-none ",
  tdnumber: "px-6 py-4 text-right",
  darkBlue: "bg-blue-700 text-white hover:bg-blue-800 focus:ring-blue-700",
  darkRed: "bg-red-700 text-white hover:bg-red-800 focus:ring-red-700",
  darkGreen: "bg-green-700 text-white hover:bg-green-800 focus:ring-green-700",
  darkNeutral: "bg-neutral-700 text-white hover:bg-neutral-800 focus:ring-neutral-700",
  dark: "bg-neutral-100 text-neutral-800 dark:bg-neutral-900 dark:text-neutral-200 hover:bg-black hover:text-white focus:ring-neutral-700",
  navactive: "text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500",
  inactive: "text-gray-600",
};

export {styleClass};